package com.example.geometryapp.Enum;


//All of the different level categories
public enum Categories {
    POINTFROMCOORDINATES,
    COORDINATESFROMPOINT,
    FINDPOINTWITHLINESYMMETRY,
    FINDCOORDINATEWITHSYMMETRY,
    FINDPOINTWITHPOINTSYMMETRY,
    FINDCOORDINATEWITHPOINTSYMMETRY,
    FINDFIGUREOFSYMMETRYTHROUGHPOINTOFSYMMETRY,
    FINDTHEPERIMETEROFAFIGURE,
    COMPLETEFIGUREFROMPERIMETER,
    FINDAREAFROMFIGURE,
    COMPLETEFIGUREFROMAREA
}
